# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Box Settings
  config.vm.box = "ubuntu/trusty64"
  
  # Provider Settings
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 512
  
	end
  
  # Network Settings

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
  # config.vm.network "private_network", ip: "10.0.0.8"
  # config.vm.network "public_network"


  # Folder Settings
  # config.vm.synced_folder "../data", "/vagrant_data"
	

  


  # Provision Settings   
  config.vm.provision "shell", inline: <<-SHELL
     
 # Update Packages
apt-get update

# Basic Linux Stuff
apt-get install -y git

# Apache
apt-get install -y apache2

# Enable Apache Mods
a2enmod rewrite

#Add Onrej PPA Repo
apt-add-repository ppa:ondrej/php
apt-get update

# Install PHP
apt-get install -y php7.2

# PHP Apache Mod
apt-get install -y libapache2-mod-php7.2

# Restart Apache
service apache2 restart

# PHP Mods
apt-get install -y php7.2-common
apt-get install -y php7.2-mcrypt
apt-get install -y php7.2-zip

# Set MySQL Pass
debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'

# Install MySQL
apt-get install -y mysql-server

# PHP-MYSQL lib
apt-get install -y php7.2-mysql

# Restart Apache
sudo service apache2 restart

# Install Firewall & Proxy
sudo apt-get install -y ufw
     ufw enable
     ufw allow 80/tcp
     ufw allow from any to any port 22
     ufw allow out 22/tcp

     apt-get install libapache2-mod-proxy-html
     apt-get install libxml2-dev

     a2enmod proxy
     a2enmod proxy_html
     a2enmod proxy_http

     sudo service apache2 restart

#Group Add
groupadd db
groupadd admin
groupadd web

#User Add
useradd dbmatt -p root
useradd dbpeter -p root
useradd webarkley -p root
useradd webwilliam -p root

#Adding User to Group
usermod -aG database dbmatt
usermod -aG database dbpeter
usermod -aG web webarkley
usermod -aG wen webwilliam

#Gruppenordner erstellen
mkdir -p /teams/db
touch /teams/db/dbconcept

mkdir -p /teams/web
touch /teams/web/webconcept

#Gruppenordner Zugriffe erteilen
chmod 770 /teams/db -R
chown root:database /teams/db/ -R

chmod 770 /teams/web -R
chown root:web /teams/web/ -R

SHELL

end