# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Box Settings
  config.vm.box = "ubuntu/trusty64"
  
  # Provider Settings
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 512
  
	end
  
  # Network Settings

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
  # config.vm.network "private_network", ip: "10.0.0.8"
  # config.vm.network "public_network"


  # Folder Settings
  # config.vm.synced_folder "../data", "/vagrant_data"
	

  


  # Provision Settings   
  config.vm.provision "shell", path: "./template/template.sh"

end